name: pkgbuild
inputs:
  platform:
    required: true
  files:
    required: true
runs:
  using: composite
  steps:
    - name: Get bootstrap kit
      uses: actions/download-artifact@v4
      with:
        name: bootstrap-kit-${{ inputs.platform }}
        path: ~/dl/

    - name: Unpack bootstrap
      shell: bash
      run: |
        tar -xvf $HOME/dl/bootstrap.tar -C /

    - name: Build packages
      shell: bash
      run: |
        PATH=$HOME/pkg/sbin:$HOME/pkg/bin:/usr/sbin:/sbin:/usr/bin:/bin
        for file in ${{ inputs.files }}; do
          echo ${file} | cut -d/ -f1,2
        done | sort | uniq | while read dir; do
          (cd ${dir} && bmake install)
        done
