name: Build and test pkgsrc commit
run-name: Testing commit ${{ github.sha }} by ${{ github.actor }}
on: [push]
jobs:
  bootstrap:
    strategy:
      matrix:
        os:
          - macos-12
          - macos-13
          - macos-14
          - ubuntu-20.04
          - ubuntu-22.04
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Identify if any bootstrap files that have changed
        id: changed-bootstrap-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            archivers/libarchive/**
            archivers/pax/**
            bootstrap/bootstrap
            devel/bmake/**
            mk/**
            pkgtools/bootstrap-extras/**
            pkgtools/bootstrap-mk-files/**
            pkgtools/cwrappers/**
            pkgtools/mktools/**
            pkgtools/pkg_install/**
            shells/mksh/**
            sysutils/bsdinstall/**
            sysutils/install-sh/**
            textproc/nbsed/**

      - name: Identify if any package files have changed
        id: changed-package-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            archivers/*/**
            audio/*/**
            benchmarks/*/**
            biology/*/**
            cad/*/**
            chat/*/**
            comms/*/**
            converters/*/**
            cross/*/**
            databases/*/**
            devel/*/**
            editors/*/**
            emulators/*/**
            filesystems/*/**
            finance/*/**
            fonts/*/**
            games/*/**
            geography/*/**
            graphics/*/**
            ham/*/**
            inputmethod/*/**
            lang/*/**
            mail/*/**
            math/*/**
            mbone/*/**
            meta-pkgs/*/**
            misc/*/**
            multimedia/*/**
            net/*/**
            news/*/**
            packages/*/**
            parallel/*/**
            pkgtools/*/**
            print/*/**
            science/*/**
            security/*/**
            shells/*/**
            sysutils/*/**
            templates/*/**
            textproc/*/**
            time/*/**
            wm/*/**
            www/*/**
            x11/*/**

      - name: Identify if bootstrap artifact already exists
        id: bootstrap-artifact
        uses: LIT-Protocol/artifact-exists-action@v0
        with:
          name: bootstrap-${{ matrix.os }}

      - name: Bootstrap if required
        id: build-bootstrap
        if: steps.changed-bootstrap-files.outputs.any_changed == 'true' || steps.bootstrap-artifact.outputs.exists == 'false'
        run: |
          cd ${{ github.workspace }}/bootstrap
          ./bootstrap --prefix=$HOME/pkg --unprivileged --make-jobs=4

      - name: Archive bootstrap kit
        id: archive-bootstrap
        if: steps.bootstrap.outcome == 'success' }}
        uses: actions/upload-artifact@v4
        with:
          name: bootstrap-${{ matrix.os }}
          path: |
            ~/pkg/

      - name: Download bootstrap kit
        if: steps.archive-bootstrap.outcome == 'skipped'
        uses: actions/download-artifact@v4
        with:
          name: bootstrap-${{ matrix.os }}

      - name: Build packages
        if: ${{ steps.changed-package-files.outputs.any_changed == 'true' }}
        env:
          CHANGED_FILES: ${{ steps.changed-package-files.outputs.all_changed_files }}
        run: |
          PATH=$HOME/pkg/sbin:$HOME/pkg/bin:$PATH
          for file in ${CHANGED_FILES}; do
            echo ${file} | cut -d/ -f1,2
          done | sort | uniq | while read dir; do
            (cd ${dir} && bmake install)
          done
