name: build-macos
on: [push]
jobs:
  build-macos-12:
    runs-on: macos-12
    steps:
      - name: Checkout pkgsrc
        uses: actions/checkout@v4
        with:
          show-progress: false
      - name: Bootstrap pkgsrc
        uses: ./.github/actions/bootstrap
        with:
          platform: macos-12-x86_64
  build-macos-13:
    runs-on: macos-13
    steps:
      - name: Checkout pkgsrc
        uses: actions/checkout@v4
        with:
          show-progress: false
      - name: Bootstrap pkgsrc
        uses: ./.github/actions/bootstrap
        with:
          platform: macos-13-x86_64
  build-macos-14:
    runs-on: macos-14
    steps:
      - name: Checkout pkgsrc
        uses: actions/checkout@v4
        with:
          show-progress: false
      - name: Bootstrap pkgsrc
        uses: ./.github/actions/bootstrap
        with:
          platform: macos-14-arm64
