name: build-cross-platform
on: [push]
jobs:
  build-cross-platform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - name: freebsd
            architecture: x86-64
            version: '14.1'

          - name: freebsd
            architecture: arm64
            version: '14.1'

          - name: openbsd
            architecture: x86-64
            version: '7.5'

          - name: openbsd
            architecture: arm64
            version: '7.5'

          - name: netbsd
            architecture: x86-64
            version: '10.0'

          - name: netbsd
            architecture: arm64
            version: '10.0'

    steps:
      - name: Checkout pkgsrc
        uses: actions/checkout@v4
        with:
          show-progress: false

      - name: Test on ${{ matrix.os.name }}
        uses: cross-platform-actions/action@v0.25.0
        with:
          operating_system: ${{ matrix.os.name }}
          architecture: ${{ matrix.os.architecture }}
          version: ${{ matrix.os.version }}
          shell: bash
          run: |
            pwd
            uname
            ls
            ./.github/scripts/bootstrap.sh
