name: pkgsrc-commit-checks
on: [push]
jobs:
  #
  # Calculate what changes were made to the repository, to determine which
  # subsequent jobs should be run.
  #
  whatchanged:
    runs-on: ubuntu-latest
    outputs:
      bootstrap-hash: ${{ steps.bootstrap.outputs.hash }}
      jperkin: true
      debug: ${{ toJSON(steps) }}
      run-pkglint: ${{ steps.pkglint.outputs.any_changed }}
      pkglint-files: ${{ steps.pkglint.outputs.all_changed_files }}
      run-pkgbuild: ${{ steps.pkgpath.outputs.any_changed }}
      pkgbuild-files: ${{ steps.pkgpath.outputs.all_changed_files }}
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false
      - id: bootstrap
        run: |
          echo hash=${{ hashFiles(
            'archivers/libarchive/**',
            'archivers/pax/**',
            'bootstrap/bootstrap',
            'devel/bmake/**',
            'mk/**',
            'pkgtools/bootstrap-extras/**',
            'pkgtools/bootstrap-mk-files/**',
            'pkgtools/cwrappers/**',
            'pkgtools/mktools/**',
            'pkgtools/pkg_install/**',
            'shells/mksh/**',
            'sysutils/bsdinstall/**',
            'sysutils/install-sh/**',
            'textproc/nbsed/**') }} >> "$GITHUB_OUTPUT"
      - id: pkglint
        uses: tj-actions/changed-files@v44
        with:
          files_ignore: |
            .github/**
            README.md
            _NetBSD-pkgdb
            doc/**
            pkglocate
      - id: pkgpath
        uses: tj-actions/changed-files@v44
        with:
          files_ignore: |
            */Makefile
            .github/**
            Makefile
            README.*
            _NetBSD-pkgdb
            bootstrap/**
            distfiles/**
            doc/**
            licenses/**
            mk/**
            pkglocate
            regress/**
  showvars:
    runs-on: ubuntu-latest
    needs: whatchanged
    steps:
      - run: |
          echo "${{ toJSON(needs.whatchanged) }}"
          echo 1=${{ needs.whatchanged }}
          echo 2=${{ needs.whatchanged.outputs }}
          echo 3=${{ needs.whatchanged.outputs.bootstrap-hash }}
          echo 4=${{ needs.whatchanged.outputs.run-pkgbuild }}
          echo 5=${{ needs.whatchanged.outputs.pkgbuild-files }}
          echo 6=${{ needs.whatchanged.outputs.run-pkglint }}
          echo 7=${{ needs.whatchanged.outputs.pkglint-files }}

  # pkglint only needs to run once on any OS so just use latest Ubuntu.
  pkglint:
    runs-on: ubuntu-latest
    needs: whatchanged
    if: needs.whatchanged.outputs.run-pkglint == 'true'
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false
      - uses: ./.github/actions/pkglint

  #
  # Builds
  #
  build-ubuntu-24-x86_64:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false
      - uses: ./.github/actions/bootstrap
        with:
          platform: ubuntu-24-x86_64
  build-netbsd-10-x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false
      - uses: cross-platform-actions/action@v0.25.0
        with:
          operating_system: netbsd
          architecture: x86-64
          version: '10.0'
          shell: bash
          run: |
            ./.github/scripts/bootstrap.sh
      - uses: actions/upload-artifact@v4
        with:
          name: bootstrap-kit-netbsd-x86_64
