name: pkgsrc-commit-checks
on: [push]
jobs:
  #
  # pkglint only needs to run once on any OS
  #
  pkglint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false
      - uses: ./.github/actions/pkglint
  #
  # Calculate what changes were made to the repository.
  #
  whatchanged:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false
        outputs:
          bootstrap-hash: ${{ hashFiles(
            'archivers/libarchive/**',
            'archivers/pax/**',
            'bootstrap/bootstrap',
            'devel/bmake/**',
            'mk/**',
            'pkgtools/bootstrap-extras/**',
            'pkgtools/bootstrap-mk-files/**',
            'pkgtools/cwrappers/**',
            'pkgtools/mktools/**',
            'pkgtools/pkg_install/**',
            'shells/mksh/**',
            'sysutils/bsdinstall/**',
            'sysutils/install-sh/**',
            'textproc/nbsed/**') }}
      # Were any package directories modified?
      - uses: tj-actions/changed-files@v44
        with:
          files_ignore: |
            */Makefile
            .github/**
            Makefile
            README.*
            _NetBSD-pkgdb
            bootstrap/**
            distfiles/**
            doc/**
            licenses/**
            mk/**
            pkglocate
            regress/**
  #
  # Builds
  #
  build-ubuntu-24-x86_64:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false
      - uses: ./.github/actions/bootstrap
        with:
          platform: ubuntu-24-x86_64
  build-netbsd-10-x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false
      - uses: cross-platform-actions/action@v0.25.0
        with:
          operating_system: netbsd
          architecture: x86-64
          version: '10.0'
          shell: bash
          run: |
            ./.github/scripts/bootstrap.sh
      - uses: actions/upload-artifact@v4
        with:
          name: bootstrap-kit-netbsd-x86_64
