name: pkgsrc-commit-checks
on: [push]
jobs:
  #
  # Verify commit message conforms to our standards.
  #
  commit-message:
    runs-on: ubuntu-latest
    steps:
      - uses: gsactions/commit-message-checker@v2
        with:
          pattern: '^[^#].{1,50}'
          error: 'First line should not exceed 50 characters'
          flags: 'gm'
          excludeDescription: 'true'
      - uses: gsactions/commit-message-checker@v2
        with:
          pattern: ': .+$'
          error: 'First line should match "pkg: description"'
          flags: 'gm'
          excludeDescription: 'true'
      - uses: gsactions/commit-message-checker@v2
        with:
          pattern: '^[^#].{1,78}'
          error: 'The maximum line length of 78 characters is exceeded.'
          flags: 'gm'

  #
  # Calculate what changes were made to the repository, to determine which
  # subsequent jobs should be run.
  #
  what-changed:
    runs-on: ubuntu-latest
    # There's surely a DRY way to do this?
    outputs:
      bootstrap-hash: ${{ steps.what-changed.outputs.bootstrap-hash }}
      run-pkglint: ${{ steps.what-changed.outputs.run-pkglint }}
      pkglint-files: ${{ steps.what-changed.outputs.pkglint-files }}
      run-pkgbuild: ${{ steps.what-changed.outputs.run-pkgbuild }}
      pkgbuild-files: ${{ steps.what-changed.outputs.pkgbuild-files }}
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false
      - id: what-changed
        uses: ./.github/actions/what-changed
  show-vars:
    runs-on: ubuntu-latest
    needs: what-changed
    steps:
      - name: Debug variables from what-changed
        run: |
          echo "${{ toJSON(needs.what-changed) }}"

  #
  # Run pkglint if any files changed that need testing.
  #
  pkglint:
    runs-on: ubuntu-latest
    needs: what-changed
    if: needs.what-changed.outputs.run-pkglint == 'true'
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false
      - uses: ./.github/actions/pkglint

  #
  # Builds
  #
  build-macos-13-arm64:
    runs-on: macos-13
    needs: what-changed
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false
      - uses: ./.github/actions/bootstrap
        with:
          platform: macos-13-arm64
          hash: ${{ needs.what-changed.outputs.bootstrap-hash }}
      - uses: ./.github/actions/pkgbuild
        if: needs.what-changed.outputs.run-pkgbuild == 'true'
        with:
          platform: macos-13-arm64
          files: ${{ needs.what-changed.outputs.pkgbuild-files }}

  build-ubuntu-24-x86_64:
    runs-on: ubuntu-24.04
    needs: what-changed
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false
      - uses: ./.github/actions/bootstrap
        with:
          platform: ubuntu-24-x86_64
          hash: ${{ needs.what-changed.outputs.bootstrap-hash }}
      - uses: ./.github/actions/pkgbuild
        if: needs.what-changed.outputs.run-pkgbuild == 'true'
        with:
          platform: ubuntu-24-x86_64
          files: ${{ needs.what-changed.outputs.pkgbuild-files }}

  build-netbsd-10-x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false
      - uses: cross-platform-actions/action@v0.25.0
        with:
          operating_system: netbsd
          architecture: x86-64
          version: '10.0'
          shell: bash
          run: |
            ./.github/scripts/bootstrap.sh
      - uses: actions/upload-artifact@v4
        with:
          name: bootstrap-kit-netbsd-x86_64
