name: pkgsrc-commit-checks
on: [push]
jobs:
  #
  # Calculate what changes were made to the repository, to determine which
  # subsequent jobs should be run.
  #
  what-changed:
    runs-on: ubuntu-latest
    outputs:
      blah: ${{ steps.what-changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false
      - id: what-changed
        uses: ./.github/actions/what-changed

  showvars:
    runs-on: ubuntu-latest
    needs: what-changed
    steps:
      - run: |
          echo "${{ toJSON(needs.what-changed) }}"

  pkglint:
    runs-on: ubuntu-latest
    needs: what-changed
    if: needs.what-changed.outputs.run-pkglint == 'true'
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false
      - uses: ./.github/actions/pkglint

  #
  # Builds
  #
  build-ubuntu-24-x86_64:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false
      - uses: ./.github/actions/bootstrap
        with:
          platform: ubuntu-24-x86_64
  build-netbsd-10-x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false
      - uses: cross-platform-actions/action@v0.25.0
        with:
          operating_system: netbsd
          architecture: x86-64
          version: '10.0'
          shell: bash
          run: |
            ./.github/scripts/bootstrap.sh
      - uses: actions/upload-artifact@v4
        with:
          name: bootstrap-kit-netbsd-x86_64
