name: pkglint
on: [push]
env:
  PKGLINT_VERSION: v23.5.0
jobs:
  pkglint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pkgsrc
        uses: actions/checkout@v4

      - name: Use cached pkglint build if available
        id: pkglint-binary
        uses: actions/cache@v4
        with:
          key: pkglint-${{ env.PKGLINT_VERSION }}
          path: ~/go/bin/pkglint

      - name: Checkout pkglint
        if: steps.pkglint-binary.outputs.cache-hit != 'true'
        uses: actions/checkout@v4
        with:
          repository: rillig/pkglint
          path: pkglint
          ref: ${{ env.PKGLINT_VERSION }}

      - name: Build pkglint
        if: steps.pkglint-binary.outputs.cache-hit != 'true'
        run: |
          cd pkglint/v23
          go install -v ./...

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files_ignore: |
            .github/**
            README.md
            _NetBSD-pkgdb
            doc/**
            pkglocate

      - name: Run pkglint
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          $HOME/go/bin/pkglint -Wall -Werror -e ${CHANGED_FILES}
