name: Verify pkglint
run-name: Linting ${{ github.sha }} by ${{ github.actor }}
on: [push]
jobs:
  pkglint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pkgsrc
        uses: actions/checkout@v4

      - name: Checkout pkglint
        uses: actions/checkout@v4
        with:
          repository: rillig/pkglint
          path: pkglint

      - name: Build latest pkglint
        run: |
          cd pkglint/v23
          go install -v ./...

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44

      - name: Run pkglint
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            $HOME/go/bin/pkglint -Wall ${file}
          done
