name: test
on:
  push:
    branches:
      - trunk
      - 'ci/**'
  workflow_dispatch:
jobs:
  what-changed:
    runs-on: ubuntu-latest
    outputs:
      bootstrap-hash: ${{ steps.what-changed.outputs.bootstrap-hash }}
      pkgbuild-files: ${{ steps.what-changed.outputs.pkgbuild-files }}
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false
      - uses: pkgsrc-ci/what-changed@v1
        id: what-changed
  bootstrap:
    needs: what-changed
    uses: ./.github/workflows/bootstrap.yml
    with:
      bootstrap-hash: ${{ needs.what-changed.outputs.bootstrap-hash }}
  log:
    needs: what-changed
    runs-on: ubuntu-latest
    steps:
      - name: do stuff
        shell: bash
        run: |
          set | grep GITHUB_
          cat >n <<-EOF
          ${{ toJSON(needs.what-changed) }}
          EOF
          cat n
          cat >t <<-EOF
          ${{ toJSON(github.event) }}
          EOF
          cat t
